( This gcode generated by /Applications/EAGLE/ulp/pcb-gcode.ulp )
( Copyright 2005 by John Johnson. See readme.txt for licensing terms. )

( This file generated from the board /Users/gregorywitt/Documents/eagle/color factory/dontlook.brd )
( This file generated 1/30/10 6:39 PM )

G20

G90
G00 Z0.5000 
G00 X0 Y0
M03
G04 P3.000000
(File Footer)
G00 Z0.5000 
M05
M02
